### ISSUE TITLE
waitFor is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by bph** [artpi/roam-research-private-api#5]
After calling the `roam-quick` command a notification was displayed: 
`waitFor` is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.

**Comment by artpi** [comment]
Thank you @bph !
I just pushed version 0.9.0 which fixes that and adds so much more. In particular - the command line tool is now very powerful

**Comment by artpi** [comment]
But I also deprecated `roam-quick`. Instead i recommend using `roam-api create`

**Comment by bph** [comment]
Awesome!  Can't wait to learn more... Thank you!
